# Generated by Django 5.1.1 on 2024-09-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanitationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_amo', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('commune', models.CharField(max_length=255)),
                ('fokontany', models.CharField(max_length=255)),
                ('localite', models.CharField(max_length=255)),
            ],
        ),
    ]
